@env = LocalEnv

### Testing if the server is running
# @name health
GET {{hostname}}/api/healthz

### Reset the database
# @name reset
POST {{hostname}}/admin/reset

### Create a new user
# @name create_user

POST {{hostname}}/api/users
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Login and store tokens
# @name login
POST {{hostname}}/api/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% 
  client.global.set("access_token", response.body.token);
  client.global.set("refresh_token", response.body.refresh_token);
  client.log("Access token:", client.global.get("access_token"));
%}


### Use refresh token to get a new access token
# @name refresh
POST {{hostname}}/api/refresh
Content-Type: application/json
Authorization: Bearer 83a706193af4ca40c499fdede51735cb

> {% 
  client.global.set("access_token", response.body.token);
%}


### Get all chirps
GET {{hostname}}/api/chirps
