// This file is a collection of HTTP request for testing purposes

// Standard access to the file server
http://localhost:8080/app/

###
// Access to assets endpoint
http://localhost:8080/app/assets

###
// Server readiness check
GET http://localhost:8080/api/healthz

###
// Access to counter
GET http://localhost:8080/admin/metrics 

###
// Reset database
POST http://localhost:8080/admin/reset 

###
// Creates a user #1
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "password": "04234",
  "email": "lane@example.com"
}

###
// Creates a user #2
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "saul@bettercall.com"
}

###
// Create a test chirp
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "60ff039b-164a-4371-9002-3ee89517c2ac"
}

###
// Get all chirps
GET http://localhost:8080/api/chirps

###
// Get a specific chirp (check psql chirpy for valid ID)
GET http://localhost:8080/api/chirps/faa768b7-855f-4472-a7c6-e7d6ba44cb55

###
// 6f7ea7dc-7208-4c59-a3ce-38362b78012c <- ID for lane@example.com>
// Try the login api
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
 "email": "lane@example.com",
 "password": "042341"
}