// This file is a collection of HTTP request for testing purposes

// Standard access to the file server
http://localhost:8080/app/

###
// Access to assets endpoint
http://localhost:8080/app/assets

###
// Server readiness check
GET http://localhost:8080/api/healthz

###
// Access to counter
GET http://localhost:8080/admin/metrics 

###
// Reset database
POST http://localhost:8080/admin/reset 

###
// Creates a user #1
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "someoneelse@example.com"
}

###
// Creates a user #2
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "saul@bettercall.com"
}

###
// Create a test chirp
POST http://localhost:8080/api/chirps
Content-Type: 

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "06c052a5-806b-4b38-a221-97b04d46f8b7"
}